version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    groups:
      # Group all patch updates together
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
