import random_default from "random";

export const patches = [
  "#1 Worker",
  "Blood Type",
  "Biohazard Symbol",
  "Nuclear Symbol",
  "Be Sure: Doubletap",
  "Smiley Face (Glow In The Dark)",
  "Jolly Roger",
  "Queen Of Hearts",
  "Pin-Up (Riding Missile)",
  "I'm A (Love) Machine",
  "Hello My Name Is:",
  "Take Me To Your Leader (Ufo)",
  "Take My Life (Please)",
  "Fix Me First (Caduceus)",
  "Nasa Logo",
  "Dove In Crosshairs",
  "Welcome To The Danger Zone",
  "Pin-Up (Succubus)",
  "Drink / Fight / Fuck",
  "Mudflap Girl",
  "Game Over (Bride & Groom)",
  "Improve / Adapt / Overcome",
  "Keep Well Lubricated",
  "Plays Well With Others",
  "I Am Not A Robot",
  "I Can't Fix Stupid",
  "All Seeing Eye",
  "Nomad",
  "Loner",
  "Mama Tried",
  "My Other Ride Married You",
  "Grim Reaper Back",
  "Smooth Operator",
  "For Science!",
  "Help Wanted",
  "Dice (Snake Eyes)",
  "Good (Brain)",
  "Too Pretty To Die",
  "Icarus",
  "Risk Of Electrocution Symbol",
  "Double Cherry",
  "Solve Et Coagula (Baphomet)",
  "Security Guard",
  "Upstanding Citizen",
  "I'm Not A Rocket Scientist / But You're An Idiot",
  "Red Shirt Logo",
  "Don't Run You'll Only Die Tired",
  "Poker Hand: Dead Man's Hand",
  "Cowboy Up (Crossed Revolvers)",
  "I Am My Brother's Keeper",
  "Chibi Cthulhu",
  "Black Widow Spider",
  "Skull And Crossed Wrenches",
  "Mr. Yuck",
  "One Size Fits All (Grenade)",
  "Dilligaf?",
  "Eat The Rich",
  "Отъебись (Get Fucked, Russian)",
  "Work Hard / Party Harder",
  "Flame Emoji",
  "Atom Symbol",
  "Fun Meter (Reading: Bad Time)",
  "Smile: Big Brother Is Watching",
  "Actually, I Am A Rocket Scientist",
  "Heart",
  "Viking Skull",
  "Apex Predator",
  "(Sabertooth Skull)",
  "Pin-Up (Ace Of Spades)",
  "Princess",
  "I Like My Tools Clean / And My Lovers Dirty",
  "Good Boy",
  "Suck It Up",
  "Troubleshooter",
  "If I'm Running Keep Up Back",
  "Crossed Hammers With Wings",
  "Pin-Up (Mechanic)",
  "Travel To Distant Exotic Places / Meet Unusual Things / Get Eaten",
  "Front Towards Enemy",
  "(Claymore Mine)",
  "Bad Bitch",
  "Soviet Hammer & Sickle",
  "Fubar",
  "Fuck Forever (Roses)",
  "Live Free And Die",
  "Pin-Up (Nurse): The Louder You Scream The Faster I Come",
  "Meat Bag",
  "Medic",
  "(Skull And Crossbones On Logo)",
  "Girl's Best Friend (Diamond)",
  "Inverted Cross",
  "Do You Sign My Paychecks?",
  "I ♥ Myself",
  "'Powered By Coffee'",
  "Red Gear",
  "Do Your Job",
  "Space Is My Home (Sad Astronaut)",
  "All Out Of Fucks To Give",
  "(Astronaut With Turned Out Pockets)",
  "Allergic To Bullshit - Medical Style",
  "Any Landing Is A Good Landing",
  "Owo What's This? (Catgirl)",
  "Born To Shit / Forced To Wipe",
  "Can I Get Uuuuuuuuhhh...",
];

export class Patch {
  constructor(public name: string = Patch.choosePatch()) {}

  static choosePatch(): string {
    return random_default.choice(patches) || "No patch chosen.";
  }

  toString(): string {
    return this.name;
  }
}
