import random_default from "random";

export const trinkets = [
  "Pamphlet: Being A Good Ally To The Uplift Rights Movement",
  "Half-Empty Hot Sauce Bottle (Mild)",
  "Waterdamaged English-Hindi Phrasebook.",
  "Defused Landmine Converted Into Lunchbox",
  "Packet Of Dried Mealworms, Peanut Flavor",
  "Bottle Of Melatonin Gummies",
  "T-Shirt: Gourmet Street Summer Pub Crawl",
  "Dented Metal Water Bottle",
  "Blood Sugar Monitor",
  "Pet Rock (Actual Silicon-Based Xenofauna)",
  "Vibrant Blue Turban",
  "Box Of Mushroom Wine",
  "Collection Of Messages From Colonial Pen-Pal",
  "Noise-Cancelling Headphones",
  "Incense Sticks",
  "Human Femur, Scrimshawed",
  "Can Of Spraypaint (Fuligin)",
  "Protractor, Compass, Slide Rule",
  "Glass Bead Bracelet ( Prime Colonies)",
  "Pamphlet: Zug Facts",
  "Mummified Monkey Paw, Two Fingers Curled",
  "Encrypted Hard Drive (Personal)",
  "Bag Of Plant-Protein Jerky ",
  "Book: Plainspeak Programming Language For Beginners",
  "Uninstalled Cyber-Eye (Functional)",
  "Solid Diamond Chess Piece (Rook)",
  "Prayer Rug",
  "Ship Model (Recombination Era Ship-Of-The-Line)",
  "Logic Core With Partially-Written Ai",
  "Alien Insect Preserved In Amber",
  "Shard Of The Great Garbage Reef",
  "Collectable Holocards (Extinct Animals)",
  "Shaky Handheld Video Of A Live Thylacine",
  "Book: The Carvers: Memories Of Sunny Smiles Unicorn Farm",
  "Bag Of Plastic Dinosaurs ",
  "Miniature Crab Drone",
  "Ticket Stub: King In Yellow (Aldrin Station Community Theater)",
  "Potted Tomato Plant",
  "T-Shirt: I Had A Blast At The Iss Memorial Museum!",
  "One-Time Encrypted Pad",
  "Dollop Of Inert Grey Goo In Vial Necklace",
  "Baseball Cap (Ganymede Hammerheads)",
  "Bogo Coupon (The Chop Shop)",
  "Prop Chainsword",
  "Nova Tierra Environment Reclamation Volunteer Crew Jacket",
  "Dog Tags (Not Yours)",
  "Hrt Supplies",
  "Necklace Of Inhuman Teeth",
  "Pamphlet: Do What You Need, Not What You're Told",
  "Emergency Flare",
  "Bootleg Pocket Ai",
  "Catnip Toy",
  "Silk Handkerchief (Stolen)",
  "Sketchbook With Amateur Pornography",
  "Hand-Drawn Map Of The Core Worlds",
  "Blanket, Very Warm (Cartoon Monster)",
  "Action Figure (Space Marine)",
  "High-Glare Sunglasses",
  "Snack Bag (Heirloom Carrots)",
  "Book: Yokai Of The High Frontier",
  "Book: Fungi Of The Far Realms",
  "Pamphlet: Common Occult Vectors And Dangers",
  "Playing Cards (Classic Ships)",
  "Wikipedia Lifetime Service Award",
  "Smart-Lemur Companion",
  "Squishy Kaiju Stress Toy",
  "Young Child's Art Project",
  "Usps Mail Bag",
  "Mysterious Orb",
  "Solarian Church Comic Tracts (Bundle)",
  "Nudibranch Plushie",
  "Alpha Gaunt Action Figure (Recalled)",
  "Pamphlet: The Truth About Terraforming - A Long And Dangerous Scam",
  "Banjo",
  "Camo Poncho (Forest)",
  "Pendant Ocarina",
  "Unlabeled Vhs Tape, Contents Unknown",
  "Spaceport Diner Rewards Punchcard, 2 Punches",
  "Book: The Illustrated Upanishads",
  "Hilt Of Broken Sword",
  "Jagged Chunk Of Red Rock",
  "Japamala",
  "Once-Fashionable Shoulder Cape",
  "Wooden Box Of Loose-Leaf Tea",
  "Handheld Game Console",
  "Elephant Figurine (Wood)",
  "Comfy Knit Scarf",
  "Hymn-Book (Reformed Trappist Catholic Church)",
  "Baphomet Bobblehead",
  "Antique Pocketwatch",
  "Funeral Mask Of Unidentified Woman",
  "Journal Full Of Rpg Notes",
  "Marijuana Cigarettes ",
  "Pocket Of Weathered Coins (Assorted Make, All Worthless)",
  "T-Shirt: Born To Die World Is A Fuck",
  "Octopus Signet Ring ",
  "Book: Encounters With The Zetians",
  "Gold Lootbox, Unopened",
  "Ticket Stub: Eschatology And Genesis",
  "Horrifically Loud Floral-Print Shirt",
  "Pornographic Magazine (Chimera Morphs)",
  "Book: Language Construction For Utter Buffoons",
  "Blood-Stained Voucher ( Human Soul)",
  "Engraved Bullet ('Merry Christmas, Asshole')",
  "Centurion's Helmet",
  "Leopard Pelt (Genuine)",
  "Library Card",
  "Officer's Dress Uniform",
  "Can Of Beans",
  "Vinyl Figure (Ganesha)",
  "Mead-Horn",
  "Icon Amulet (Triple Empress)",
  "Comic Book: The Complete Inferno Girl",
  "Book: And So They Sought God",
  "Flask Of Koumis",
  "Hanafuda Cards",
  "Tricorn Hat",
  "Spacer's Tarocca Deck",
  "Satchel Bag (Red Pentagram)",
  "Shark-Tooth Necklace",
  "Archaic Vhs Tape ('The Fat Lady Sings')",
  "Goldenrod Cardigan",
  "Plague Doctor Mask (Functional)",
  "Matcha Hard Candies",
  "Dogū Figurine",
  "Box Of Toothpick-Flossers",
  "Mini Ice-Cream Maker",
  "Bead Animal (Lizard)",
  "Sprig Of Lilac (Hairpin)",
  "Sany Rungal Cassette Player",
  "Manga: My Life With The Ghosts, Vol ",
  "Pamphlet: Abducted!",
  "Obsidian Knife W/ Shoulder Harness",
  "Bag Of Protein Crisps (Chili & Chocolate)",
  "Audit Paperwork",
  "Plush Hodag",
  "Cat Ear Headband",
  "Eva Helmet (Rhinoceros Beetle)",
  "Handheld Atum-Monitor (Counterfeit)",
  "Blurry Photo Of A True Clown",
  "Portable Drive (Firebird Fork)",
  "Boomerang",
  "Book: Poetry Of The Great Whales",
  "Bag Of Trail Mix",
  "Mushroom-Cap Hat",
  "Venusian Fly Trap",
  "T-Shirt: Astrogothic",
  "Nose-Ring (Diamond)",
  "Cat Café Customer Appreciation Card",
  "Bottle Of Vodka W/ Sea Slug",
  "Machete With A Chipped Blade",
  "Hog-Hunting License",
  "Cassette Tape: Hana Buraka's Lo-Fi Mix Vol. ",
  "Cloak Of Human Skin (Willingly Given)",
  "Pocket Of Assorted Sauce Packets",
  "Pamphlet: More Than You Could Ever Earn",
  "A Lover's Note You Cannot Read",
  "Book: On The Atûmaic Mysteries",
  "Book: Art Of The Neo-Muiraite Movement",
  "Exorcism Kit (Home-Made)",
  "Book: Atlas Of The Latter Earth",
  "Makeup Case",
  "Employee Of The Month Award (Weaponized)",
  "Packet Of Crickets (Sour Cream And Onion Flavor)",
  "Sports Betting Booklet (Cheater's League)",
  "Personal Drawing Tablet",
  "Bounty Pardon Documentation",
  "Club Nova Vip Card",
  "Great Googly Moogly's Menu",
  "Business Card (Greta Von Goort, Attorney At Law)",
  "Book:  Nutrient Paste Recipes",
  "Handheld Ai Therapist",
  "Spray Hair Color (Neon Blue)",
  "T-Shirt: Red With Single White Star",
  "Centipede Bracelet",
  "Portable Drive (Detailed Speculative Evolution Project)",
  "T-Shirt: Fuck You I Survived Deathworld",
  "Tin Of Fermented Eel",
  "Map-Your-Own-Genome Kit",
  "Notepad With Computer Passwords",
  "Rubber Mosquito Mask",
  "Last Will Of Deceased Relative",
  "Stickers (Chibi Deities, X)",
  "Time Capsule (Stolen)",
  "Waitlist For Cybernetics Clinic",
  "Lucky Penny (Bullet-Dented)",
  "Ai Assistant (Historical Personage)",
  "Archaic Memory Card",
  "Novelty Cereal Cup",
  "Burner Phone",
  "Dog Collar ('Harriet')",
  "Bottle Of Soy Sauce",
  "Water-Smoothed Pebble",
  "A Key To The Vaults Of Ghlodara",
  "Brineshrimp Cakes",
  "Vaccsuit Patch Kit",
  "Decorative Horn Implants",
  "Fractal-Pattern Headscarf",
  "Preserved Insectile Aberration",
  "Alien Pressed Flower (Common)",
  "Corroded Android Logic Core",
  "Manual: Treat Your Rifle Like A Lady",
  "Calendar: Alien Pin-Up Art",
  "Holographic Serpentine Dancer",
  "Medical Container, Purple Powder",
  "Casino Playing Cards",
  "Moonstone Ring",
  "Bartender's Certification (Expired)",
  "Prospecting Mug, Dented",
  "Vantablack Marble",
  "Ashes (A Relative)",
  "Cigarettes (Grinning Skull)",
  "Rejected Application (Colony Ship)",
  "Phosphorescent Sticks, Neon",
  "Calendar: Military Battles",
  "Campaign Poster (Home Planet)",
  "Titanium Toothpick",
  "Brass Knuckles",
  "Journal Of Grudges",
  "Ball Of Assorted Gauge Wire",
  "Switchblade, Ornamental",
  "Bonsai Tree",
  "Trilobite Fossil",
  "Patched Overalls, Personalized",
  "Spiked Bracelet",
  "Spray Paint",
  "Locket, Hair Braid",
  "Blanket, Fire Retardant",
  "Bb Gun",
  "Ushanka",
  "Menthol Balm",
  "X Tarp",
  "Kukri",
  "Shiv, Sharpened Butter Knife",
  "Opera Glasses",
  "Faded Green Poker Chip",
  "Antique Company Script (Asteroid Mine)",
  "Dessicated Husk Doll",
  "Pamphlet: Android Overlords",
  "Smut (Seditious):",
  "The Captain, Ordered",
  "Key (Childhood Home)",
  "Manual: Panic: Harbinger Of Catastrophe",
  "Token: Is Your Morale Improving?",
  "Necklace Of Shell Casings",
  "Pamphlet: Signs Of Parasitical Infection",
  "Pamphlet: The Indifferent Stars",
  "Wanted Poster, Weathered",
  "Bone Knife",
  "Manual: Rich Captain, Poor Captain",
  "Pick, Miniature",
  "Dog Tags (Heirloom)",
  "Pendant: Shell Fragments Suspended In Plastic",
  "Hooded Parka, Fleece-Lined",
  "Snake Whiskey",
  "Gloves, Leather (Xenomorph Hide)",
  "Pamphlet: Zen And The Art Of Cargo Arrangement",
  "Pictorial Pornography, Dogeared, Well Thumbed",
  "Flint Hatchet",
  "Pendant: Two Astronauts Form A Skull",
  "Rubik's Cube",
  "Manual: Survival: Eat Soup With A Knife",
  "Sputnik Pin",
  "Pills: Male Enhancement, Shoddy",
  "Lagomorph Foot",
  "Fuzzy Handcuffs",
  "Manual: Mining Safety And You",
  "Pamphlet: Against Human Simulacrum",
  "Animal Skull,  Eyes, Curled Horns",
  "Stylized Cigarette Case",
  "Trucker Cap, Mesh, Grey Alien Logo",
  "Spanner",
  "Pith Helmet",
  "Bent Wrench",
  "Powdered Xenomorph Horn",
  "I Ching, Missing Sticks",
  "Eerie Mask",
  "Golf Club (Putter)",
  "Trench Shovel",
  "Ivory Dice",
  "Tarot Cards, Worn, Pyrite Gilded Edges",
  "Bag Of Assorted Teeth",
  "Pamphlet: A Girl In Every Port",
  "Taxidermied Cat",
  "Pamphlet: Interpreting Sheep Dreams",
  "Pair Of Shot Glasses, Spent Shotgun Shells",
  "Fleshy Thing Sealed In A Murky Jar",
  "Dnr Beacon Necklace",
  "Harmonica",
  "Manual: Spacefarer's Almanac (Out Of Date)",
  "Pamphlet: The Relic Of Flesh",
  "Miniature Chess Set, Bone, Pieces Missing",
  "Anime Body Pillow",
  "A 48 Pack Of Limited Edition Soda",
];

export class Trinket {
  constructor(public name: string = Trinket.chooseTrinket()) {}

  static chooseTrinket(): string {
    return random_default.choice(trinkets) || "No trinket chosen.";
  }

  toString(): string {
    return this.name;
  }
}
